language: php

addons:
  apt:
    update: true

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - APPLICATION=ojs BRANCH=master TEST=mysql
  - APPLICATION=ojs BRANCH=master TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - cp -r ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/sword

script: cd ~/${APPLICATION} && phpunit plugins/generic/sword/tests/*.php
